In [1]:
import numpy as np

# Ways to create numpy array

In [2]:
x1 = np.array([1,2,3,43,23,45,8,672,546])

In [3]:
x1

array([  1,   2,   3,  43,  23,  45,   8, 672, 546])

In [4]:
x1[0]

1

In [5]:
x1[-1]

546

In [6]:
x1 = np.array(list([1,2,3,43,23,45,8,672,546]))

In [7]:
x1

array([  1,   2,   3,  43,  23,  45,   8, 672, 546])

In [8]:
x_2d = np.array([[32,4,65,879,866,4343,34],[32,4,65,879,866,4343,34],[32,4,65,879,866,4343,34]])

In [9]:
x_2d

array([[  32,    4,   65,  879,  866, 4343,   34],
       [  32,    4,   65,  879,  866, 4343,   34],
       [  32,    4,   65,  879,  866, 4343,   34]])

In [10]:
x2=np.arange(1,11)

In [11]:
x2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
x3 = np.arange(1,11,2)

In [13]:
x3

array([1, 3, 5, 7, 9])

In [14]:
x4=np.linspace(1,20,5)

In [15]:
x4

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [16]:
1.7755102-1.3877551

0.38775510000000013

In [17]:
x4=np.linspace(1,20,num=15)

In [18]:
x4

array([ 1.        ,  2.35714286,  3.71428571,  5.07142857,  6.42857143,
        7.78571429,  9.14285714, 10.5       , 11.85714286, 13.21428571,
       14.57142857, 15.92857143, 17.28571429, 18.64285714, 20.        ])

In [19]:
x4=np.zeros((4,5))

In [20]:
x4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
x4=np.ones((4,5))

In [22]:
x4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.empty((4,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06810132e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [24]:
np.random.random((4,4))

array([[0.90922535, 0.17990765, 0.02048704, 0.22133782],
       [0.78005942, 0.40734381, 0.53737624, 0.87543647],
       [0.98476234, 0.03337084, 0.57224681, 0.09492593],
       [0.29344123, 0.08035056, 0.63874257, 0.54769736]])

In [25]:
np.random.randn(4,4)

array([[ 0.68317594,  0.32815616, -0.88103002,  1.894044  ],
       [-0.80237811, -0.99127203,  1.04966596, -0.03908712],
       [-1.4358254 ,  1.22957138, -0.97366018, -0.54378377],
       [-1.08004114, -1.11318838,  2.02038527, -0.03084015]])

In [26]:
np.random.randint(-10,10,(5,5))

array([[-3,  9,  6, -3,  4],
       [-6, -5,  8, -3,  5],
       [ 2,  0,  8,  8, -3],
       [-6,  1,  7,  4,  2],
       [ 5, -7,  6, -1, -9]])

In [27]:
x = np.random.randint(-10,10,(5,5))

In [28]:
np.shape(x)

(5, 5)

In [29]:
x.reshape(1,25)

array([[ -4,   3,  -5,  -8,  -5,  -6,  -2,  -9,  -3, -10,  -8,  -2,   8,
          4,  -5,   8,   0,   2,  -4,  -6,   4, -10,   0,  -8,   2]])

In [30]:
x.flatten()

array([ -4,   3,  -5,  -8,  -5,  -6,  -2,  -9,  -3, -10,  -8,  -2,   8,
         4,  -5,   8,   0,   2,  -4,  -6,   4, -10,   0,  -8,   2])

In [31]:
x = np.random.randint(1,10,(4,4))

In [32]:
x

array([[2, 5, 4, 2],
       [2, 9, 6, 3],
       [6, 5, 1, 8],
       [4, 5, 6, 5]])

In [33]:
x.T

array([[2, 2, 6, 4],
       [5, 9, 5, 5],
       [4, 6, 1, 6],
       [2, 3, 8, 5]])

In [34]:
x = np.arange(1,11)

In [35]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
mean = np.mean(x)

In [37]:
mean

5.5

In [38]:
median = np.median(x)

In [39]:
median

5.5

In [40]:
np.std(x)#Standard Deviation of X

2.8722813232690143

In [41]:
np.min(x)

1

In [42]:
np.max(x)

10

In [43]:
np.sum(x)

55

In [44]:
x = np.random.randint(-10,10,10)

In [45]:
x

array([-6, -3,  8,  2, -8, -4,  5,  0, -4, -8])

In [46]:
np.sort(x)

array([-8, -8, -6, -4, -4, -3,  0,  2,  5,  8])

In [47]:
x

array([-6, -3,  8,  2, -8, -4,  5,  0, -4, -8])

In [48]:
np.min(x)

-8

In [49]:
np.argmin(x)

4

In [50]:
np.argmax(x)

2

In [51]:
np.argsort(x)

array([4, 9, 0, 5, 8, 1, 7, 3, 6, 2], dtype=int64)

In [52]:
x

array([-6, -3,  8,  2, -8, -4,  5,  0, -4, -8])

In [53]:
x = np.random.randint(1,10,(5,5))

In [54]:
x

array([[6, 5, 2, 3, 4],
       [6, 5, 8, 5, 9],
       [8, 6, 6, 7, 4],
       [3, 6, 5, 3, 6],
       [9, 9, 7, 4, 1]])

In [55]:
np.mean(x,axis=1)#(row wise)

array([4. , 6.6, 6.2, 4.6, 6. ])

In [56]:
np.sum(x,axis=1)

array([20, 33, 31, 23, 30])

In [57]:
x

array([[6, 5, 2, 3, 4],
       [6, 5, 8, 5, 9],
       [8, 6, 6, 7, 4],
       [3, 6, 5, 3, 6],
       [9, 9, 7, 4, 1]])

In [58]:
new_row = np.array([[1,2,3,4,5]])

In [59]:
np.concatenate((x,new_row))

array([[6, 5, 2, 3, 4],
       [6, 5, 8, 5, 9],
       [8, 6, 6, 7, 4],
       [3, 6, 5, 3, 6],
       [9, 9, 7, 4, 1],
       [1, 2, 3, 4, 5]])

In [60]:
x = np.array([[1,2],[3,4]])

In [61]:
y = np.array([[5,6],[7,8]])

In [62]:
x

array([[1, 2],
       [3, 4]])

In [63]:
y = np.array([[5,6],[7,8]])

In [64]:
np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [65]:
np.vstack((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
x

array([[1, 2],
       [3, 4]])

In [67]:
y

array([[5, 6],
       [7, 8]])

In [68]:
x = np.array([[1,2],[3,4]])

In [69]:
x

array([[1, 2],
       [3, 4]])

In [70]:
y = np.array([[5,6],[7,8]])

In [71]:
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [72]:
x=np.random.randint(1,10,5)

In [73]:
x

array([3, 1, 8, 5, 8])

In [74]:
np.random.seed(10)

In [75]:
x=np.random.randint(1,10,5)

In [76]:
x

array([5, 1, 2, 1, 2])

In [77]:
x = np.random.randint(1,50,15)

In [78]:
x

array([ 9, 10,  1, 43, 41, 37, 17, 37, 48, 12, 25, 44, 34,  9, 37])

In [79]:
x[0:10]

array([ 9, 10,  1, 43, 41, 37, 17, 37, 48, 12])

In [80]:
x = np.array([[1,2],[3,4]])

In [81]:
x

array([[1, 2],
       [3, 4]])

In [82]:
x[1][1]

4

In [83]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [84]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [87]:
x[3,2]

12

In [89]:
x[:,::-1] #-1 is for reverse

array([[ 3,  2,  1],
       [ 6,  5,  4],
       [ 9,  8,  7],
       [12, 11, 10]])